# services:
#     omar:
#         class: Aqarmap\NotificationBundle\Channels\MailChannel
#         arguments: ["@mailer"]
#    notification.example:
#        class: Aqarmap\NotificationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

